-- Fix milestones.condition_id to accept TEXT (slug) instead of UUID
-- This allows condition IDs like "spinal-cord-injury" which are generated by ConditionService
ALTER TABLE milestones 
  ALTER COLUMN condition_id TYPE TEXT;

-- Also update goals table to accept TEXT for condition references if it exists
DO $$ 
BEGIN
  IF EXISTS (
    SELECT 1 
    FROM information_schema.columns 
    WHERE table_name = 'goals' 
    AND column_name = 'condition_id'
  ) THEN
    ALTER TABLE goals ALTER COLUMN condition_id TYPE TEXT;
  END IF;
END $$;
