// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG59Gmrs0dGkv_IvT_W1TCWc_CIoZGkY4',
    appId: '1:586562230278:web:fa896f5be64aa02d378b87',
    messagingSenderId: '586562230278',
    projectId: 'pbapblaxya4oyejmhxd5b9o6za4nbr',
    authDomain: 'pbapblaxya4oyejmhxd5b9o6za4nbr.firebaseapp.com',
    storageBucket: 'pbapblaxya4oyejmhxd5b9o6za4nbr.firebasestorage.app',
    measurementId: 'G-6X8VVKC5DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQC9mUBuLJyUUf41p_qwBvTB5UAX0Xv2U',
    appId: '1:586562230278:android:63182c2aa11509cc378b87',
    messagingSenderId: '586562230278',
    projectId: 'pbapblaxya4oyejmhxd5b9o6za4nbr',
    storageBucket: 'pbapblaxya4oyejmhxd5b9o6za4nbr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuQLn2CSFuqbH8HE7S6eXs4MkX_EyS6MI',
    appId: '1:586562230278:ios:a69185f289ffdcf4378b87',
    messagingSenderId: '586562230278',
    projectId: 'pbapblaxya4oyejmhxd5b9o6za4nbr',
    storageBucket: 'pbapblaxya4oyejmhxd5b9o6za4nbr.firebasestorage.app',
    iosClientId: '586562230278-tlejrhfmb5rmg2rh43pa1kchikqht5pu.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.CounterApp',
  );

}